/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/commission` | `/commission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/members` | `/members`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profit-logs` | `/profit-logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/strategies` | `/strategies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/unsubscribe` | `/unsubscribe`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/commission` | `/commission`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/members` | `/members`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profit-logs` | `/profit-logs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/strategies` | `/strategies`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/unsubscribe` | `/unsubscribe`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/commission${`?${string}` | `#${string}` | ''}` | `/commission${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/members${`?${string}` | `#${string}` | ''}` | `/members${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profit-logs${`?${string}` | `#${string}` | ''}` | `/profit-logs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/strategies${`?${string}` | `#${string}` | ''}` | `/strategies${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/subscriptions${`?${string}` | `#${string}` | ''}` | `/subscriptions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/unsubscribe${`?${string}` | `#${string}` | ''}` | `/unsubscribe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/commission` | `/commission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/members` | `/members`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profit-logs` | `/profit-logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/strategies` | `/strategies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/unsubscribe` | `/unsubscribe`; params?: Router.UnknownInputParams; };
    }
  }
}
